from pathlib import Path
import json
p=Path('/mnt/data/v12.13-work/src/data/react.js')
s=p.read_text()
lessons=[
('react-081','L2','Feature-based component organization','Architecture','Organizing React by business feature keeps related UI, hooks, API calls and tests close together and reduces cross-feature coupling.','A feature such as orders can contain its page, components, hooks, API client functions and tests. Shared primitives remain in a separate common layer.','src/features/orders/\n  OrdersPage.jsx\n  OrderTable.jsx\n  useOrders.js\n  ordersApi.js\n  OrdersPage.test.jsx','For a growing application, I prefer feature-oriented boundaries because they map code ownership to business capabilities and make changes easier to localize.',['Feature folder vs layer folder?','What belongs in shared code?'],['Do not put every component into one global components folder.','Do not create shared abstractions before reuse is clear.']),
('react-082','L2','Container and presentational responsibilities','Architecture','A useful separation is to keep data orchestration and stateful behavior distinct from reusable presentation, while avoiding rigid two-component rules everywhere.','A page or feature hook can fetch and transform data, while focused components receive data and callbacks. Modern React often uses custom hooks and composition instead of the old container-component pattern.','function OrdersPage() {\n  const { orders, loading } = useOrders();\n  return <OrderTable orders={orders} loading={loading} />;\n}','I separate responsibilities around behavior and reuse, not around an arbitrary rule that every component must be either container or presentational.',['When would you keep logic together?','How do custom hooks change this pattern?'],['Do not create layers just for ceremony.']),
('react-083','L2','Reusable form architecture','Forms','Large forms become difficult when field state, validation, submission and server errors are mixed together.','Keep field values and validation rules predictable, isolate reusable field components, and represent server validation errors separately from client validation errors.','function Field({ label, error, ...props }) {\n  return <label>{label}<input {...props} aria-invalid={!!error}/>{error && <span>{error}</span>}</label>;\n}','For production forms, I separate field state, validation and server errors so each concern has a clear owner and the UI can report the right failure.',['Controlled vs uncontrolled forms?','How do you handle server validation?'],['Do not assume client validation replaces backend validation.']),
('react-084','L2','API client layer in React applications','Data Fetching','Centralizing HTTP behavior avoids duplicating URL construction, headers, error parsing and authentication handling across components.','Components or hooks call feature-specific API functions. The API layer handles transport concerns while UI code handles user-facing state.','export async function getOrders(signal) {\n  const res = await fetch(\'/api/orders\', { signal });\n  if (!res.ok) throw new Error(`HTTP ${res.status}`);\n  return res.json();\n}','I keep HTTP transport details out of presentation components. That makes API behavior easier to test and change without rewriting the UI.',['Where should auth headers be added?','How do you test the API layer?'],['Do not hide business logic inside a generic HTTP helper.']),
('react-085','L2','Query state versus server state','Data Fetching','URL query parameters and server data represent different kinds of state and should not automatically be copied into multiple local states.','Use the URL for shareable navigation state such as filters or page number. Treat fetched data as server state with explicit loading, stale and error semantics.','const params = new URLSearchParams({ page: String(page), q: query });\nwindow.history.replaceState(null, \'\', `?${params}`);','I decide where state belongs based on ownership and lifetime: URL state is shareable navigation state, while server data belongs to a data-fetching strategy.',['What should be in local state?','Why avoid duplicated state?'],['Do not keep the same value independently in URL, component state and server cache without a synchronization plan.']),
('react-086','L2','Caching server data','Data Fetching','Caching server responses can avoid repeated requests and make navigation feel faster, but cached data needs freshness and invalidation rules.','A server-state library or a carefully designed cache can deduplicate requests, track stale data and refetch after mutations.','// Conceptual\n// query: orders\n// mutation: updateOrder\n// invalidate: orders','I treat server data differently from local UI state. The important questions are freshness, deduplication, invalidation and refetch behavior.',['Client cache vs browser HTTP cache?','When should data be invalidated?'],['Do not assume cached data is always current.']),
('react-087','L2','Optimistic mutation with rollback','Data Fetching','Optimistic UI updates the screen before the server confirms a mutation, then rolls back or reconciles if the request fails.','Capture the previous state, apply the expected change, send the request, and restore or refetch when the server rejects it.','setOrders(prev => prev.map(o => o.id === id ? { ...o, status: \'cancelled\' } : o));\ntry { await cancelOrder(id); } catch { await refetch(); }','Optimistic updates improve perceived latency, but I only use them when the expected result is predictable and failure recovery is clear.',['When should you avoid optimistic UI?','How do you prevent duplicate mutations?'],['Do not show success permanently before the server confirms the operation.']),
('react-088','L2','Reusable modal and portal pattern','UI Patterns','A modal often needs to escape normal layout stacking and should manage focus, dismissal and accessibility.','Render modal content through a portal into a dedicated DOM node, lock or manage background interaction, and restore focus when it closes.','createPortal(\n  <dialog open aria-modal="true">Confirm deletion?</dialog>,\n  document.getElementById(\'modal-root\')\n);','A production modal is more than a div with z-index. I consider portal placement, focus management, keyboard dismissal and accessibility.',['Why use a portal?','How do you trap focus?'],['Do not rely only on z-index to solve every overlay problem.']),
('react-089','L2','Accessible React components','Accessibility','React applications should expose semantic HTML, labels, keyboard behavior and useful state information to assistive technologies.','Prefer native elements when possible, associate labels with controls, use buttons for actions, and add ARIA only when native semantics are insufficient.','<label htmlFor="email">Email</label>\n<input id="email" name="email" />','I start with semantic HTML and keyboard accessibility, then use ARIA to fill genuine semantic gaps rather than using ARIA as decoration.',['How do you test accessibility?','Button vs div with onClick?'],['Do not use clickable divs when a button or link is appropriate.']),
('react-090','L2','Keyboard navigation and focus management','Accessibility','Single-page applications can change content without a full browser navigation, so focus management becomes part of the user experience.','After route or modal changes, move focus intentionally to the relevant heading or control when appropriate and ensure all interactive elements are keyboard reachable.','useEffect(() => {\n  headingRef.current?.focus();\n}, [location.pathname]);','I treat focus as UI state that needs deliberate management when the application changes context without a full page reload.',['How do you manage focus after form errors?','What is a roving tabindex?'],['Do not steal focus on every render.']),
('react-091','L2','Error states that users can recover from','UX Patterns','A useful error state explains what failed and gives the user an appropriate recovery action.','Distinguish validation errors, authorization failures, transient network errors and unexpected application errors, then provide context-specific actions.','if (error.code === \'NETWORK\') {\n  return <RetryPanel onRetry={reload} />;\n}','I avoid a generic error message for every failure. The UI should tell the user what they can do next while keeping technical details out of the screen.',['Where should logging happen?','How do you handle 401 vs 500?'],['Do not expose stack traces or internal exception details.']),
('react-092','L2','Loading skeletons versus spinners','UX Patterns','Loading feedback should match the expected wait and preserve layout stability when possible.','Skeletons work well for content-heavy regions because they reserve space; spinners are useful for short actions or small regions.','return loading ? <OrderTableSkeleton /> : <OrderTable rows={orders} />;','I choose loading feedback based on context and layout stability, not because one pattern is universally better.',['How do you avoid layout shift?','When should a button show a spinner?'],['Do not block the entire application for a request that only affects one panel.']),
('react-093','L2','Debounced search with request cancellation','Data Fetching','Search boxes often generate many requests; debouncing reduces traffic and cancellation prevents older results from winning a race.','Wait briefly after input stops, create an AbortController for each request, and abort the previous request when a new search begins.','const controller = new AbortController();\nfetch(`/api/search?q=${encodeURIComponent(q)}`, { signal: controller.signal });','For live search I combine debouncing with cancellation so the backend gets fewer requests and stale responses cannot overwrite newer results.',['Debounce vs throttle?','What happens when AbortController aborts?'],['Debouncing alone does not guarantee response ordering.']),
('react-094','L2','Pagination strategies in React','Data Fetching','Pagination can be page-based or cursor-based, and the UI must keep its query state synchronized with the backend contract.','Page pagination is simple for stable datasets. Cursor pagination is often better for large or frequently changing datasets because the cursor represents a position in an ordered result set.','GET /api/orders?page=2&size=20\nGET /api/orders?cursor=eyJpZCI6MTIzfQ==&limit=20','I choose pagination based on data volatility and API requirements rather than assuming page numbers are always sufficient.',['Offset vs cursor pagination?','How do you preserve filters when changing pages?'],['Do not use an unstable sort with cursor pagination.']),
('react-095','L2','File upload progress and cancellation','Data Fetching','File uploads need client-side validation, progress feedback and cancellation in addition to the normal request lifecycle.','Use FormData for multipart requests, track upload progress with a suitable HTTP API, validate file size/type, and allow cancellation where the UX requires it.','const form = new FormData();\nform.append(\'file\', file);\nawait fetch(\'/api/files\', { method: \'POST\', body: form });','I treat file upload as a workflow with validation, progress, cancellation and backend validation rather than as a normal JSON POST.',['How do you upload multiple files?','Where should file type validation happen?'],['Client-side file validation is only a UX check; the server must validate too.']),
('react-096','L3','Frontend authorization versus backend authorization','Security','Frontend authorization improves UX by hiding or disabling actions, but it cannot enforce security by itself.','The backend remains the source of truth for authorization. React can use claims or permissions to decide what to render, while every protected API verifies authorization independently.','{canDelete && <button onClick={deleteOrder}>Delete</button>}','I use frontend authorization for user experience, but I never trust it as a security boundary. The Spring backend must enforce the permission on the API.',['Where should roles be stored?','How should the UI handle 403?'],['Never assume hiding a button protects an endpoint.']),
('react-097','L3','Frontend environment configuration','Deployment','React builds often need environment-specific API URLs and feature settings without hardcoding production values into components.','Use the build tool environment mechanism, validate required variables, and separate public configuration from secrets.','const apiBase = import.meta.env.VITE_API_BASE_URL;','I keep environment configuration outside components and remember that browser-exposed variables are not secrets.',['Where do secrets belong?','Build-time vs runtime configuration?'],['Never put private API keys or credentials into browser bundles.']),
('react-098','L3','Code splitting by route and feature','Performance','Code splitting reduces the initial JavaScript payload by loading code when it is needed.','Use dynamic imports and lazy route boundaries for large or infrequently visited features, while preloading critical paths when useful.','const AdminPage = lazy(() => import(\'./AdminPage.jsx\'));','I split code around user journeys and large features, then measure whether the smaller initial bundle improves real performance.',['What is preloading?','How do Suspense boundaries affect UX?'],['Do not create hundreds of tiny chunks without measuring network overhead.']),
('react-099','L3','React application observability','Production','Frontend observability connects user-visible failures and performance problems to actionable diagnostics.','Capture structured errors, route context, request identifiers and performance signals while removing sensitive data. Correlate frontend errors with backend logs when possible.','console.error({ event: \'checkout_failed\', orderId });','For production debugging I want enough context to reproduce the issue and correlate it with backend telemetry, without logging tokens or sensitive user data.',['What should not be logged?','How do request IDs help?'],['Do not log passwords, access tokens or unnecessary personal data.']),
('react-100','L3','Designing a production React feature end-to-end','Architecture','A production React feature needs more than a component: it needs state ownership, API integration, accessibility, error handling, tests and performance considerations.','Start with the user flow and API contract, define state ownership, build accessible components, isolate data fetching, handle loading/error/empty states, test important paths, and measure performance after release.','Feature flow:\nUI → hook/API client → REST endpoint → response mapping → UI state\n+ tests + telemetry','My approach is to design the feature as a vertical slice: user experience, state, API contract, failure handling, tests and production observability all fit together.',['How would you structure a large React feature?','How would you debug it in production?'],['Do not optimize or abstract before understanding the feature requirements.'])
]

def esc(x):
    return json.dumps(x, ensure_ascii=False)
items=[]
for a in lessons:
    id,level,title,subtopic,what,how,code,delivery,followups,traps=a
    items.append('{'+','.join([f'"id":{esc(id)}',f'"level":{esc(level)}',f'"title":{esc(title)}',f'"subtopic":{esc(subtopic)}',f'"what":{esc(what)}',f'"how":{esc(how)}',f'"code":{esc(code)}',f'"delivery":{esc(delivery)}',f'"followups":{esc(followups)}',f'"traps":{esc(traps)}'])+'}')
insert=',\n'+',\n'.join(items)+'\n'
assert s.rstrip().endswith('];')
s=s.rstrip()[:-2]+insert+'];\n'
p.write_text(s)
print('added',len(lessons))
